const mapData = {
  Afghanistan: { code: 'AF', color: 'asia' },
  Albania: { code: 'AL', color: 'europe' },
  Algeria: { code: 'DZ', color: 'africa' },
  Angola: { code: 'AO', color: 'africa' },
  Argentina: { code: 'AR', color: 'southAmerica' },
  Armenia: { code: 'AM', color: 'europe' },
  Australia: { code: 'AU', color: 'oceania' },
  Austria: { code: 'AT', color: 'europe' },
  Azerbaijan: { code: 'AZ', color: 'europe' },
  Bahrain: { code: 'BH', color: 'asia' },
  Bangladesh: { code: 'BD', color: 'asia' },
  Belarus: { code: 'BY', color: 'europe' },
  Belgium: { code: 'BE', color: 'europe' },
  Benin: { code: 'BJ', color: 'africa' },
  Bhutan: { code: 'BT', color: 'asia' },
  Bolivia: { code: 'BO', color: 'southAmerica' },
  Bosnia: { code: 'BA', color: 'europe' },
  Botswana: { code: 'BW', color: 'africa' },
  Brazil: { code: 'BR', color: 'southAmerica' },
  Brunei: { code: 'BN', color: 'asia' },
  Bulgaria: { code: 'BG', color: 'europe' },
  BurkinaFaso: { code: 'BF', color: 'africa' },
  Burundi: { code: 'BI', color: 'africa' },
  Cambodia: { code: 'KH', color: 'asia' },
  Cameroon: { code: 'CM', color: 'africa' },
  Canada: { code: 'CA', color: 'northAmerica' },
  'Cape Verde': { code: 'CV', color: 'africa' },
  'Central African Republic': { code: 'CF', color: 'africa' },
  Chad: { code: 'TD', color: 'africa' },
  Chile: { code: 'CL', color: 'southAmerica' },
  China: { code: 'CN', color: 'asia' },
  Colombia: { code: 'CO', color: 'southAmerica' },
  Comoros: { code: 'KM', color: 'africa' },
  'Democratic Republic of the Congo': { code: 'CD', color: 'africa' },
  'Republic of the Congo': { code: 'CG', color: 'africa' },
  'Costa Rica': { code: 'CR', color: 'northAmerica' },
  'Ivory Coast': { code: 'CI', color: 'africa' },
  Croatia: { code: 'HR', color: 'europe' },
  Cuba: { code: 'CU', color: 'northAmerica' },
  Cyprus: { code: 'CY', color: 'europe' },
  'Czech Republic': { code: 'CZ', color: 'europe' },
  Denmark: { code: 'DK', color: 'europe' },
  Djibouti: { code: 'DJ', color: 'africa' },
  'Dominican Republic': { code: 'DO', color: 'northAmerica' },
  Ecuador: { code: 'EC', color: 'southAmerica' },
  Egypt: { code: 'EG', color: 'africa' },
  'El Salvador': { code: 'SV', color: 'northAmerica' },
  'Equatorial Guinea': { code: 'GQ', color: 'africa' },
  Eritrea: { code: 'ER', color: 'africa' },
  Estonia: { code: 'EE', color: 'europe' },
  Ethiopia: { code: 'ET', color: 'africa' },
  Fiji: { code: 'FJ', color: 'oceania' },
  Finland: { code: 'FI', color: 'europe' },
  France: { code: 'FR', color: 'europe' },
  Gabon: { code: 'GA', color: 'africa' },
  Gambia: { code: 'GM', color: 'africa' },
  Georgia: { code: 'GE', color: 'europe' },
  Germany: { code: 'DE', color: 'europe' },
  Ghana: { code: 'GH', color: 'africa' },
  Greece: { code: 'GR', color: 'europe' },
  Guatemala: { code: 'GT', color: 'northAmerica' },
  Guinea: { code: 'GN', color: 'africa' },
  'Guinea Bissau': { code: 'GW', color: 'africa' },
  Guyana: { code: 'GY', color: 'southAmerica' },
  Haiti: { code: 'HT', color: 'northAmerica' },
  Honduras: { code: 'HN', color: 'northAmerica' },
  'Hong Kong': { code: 'HK', color: 'asia' },
  Hungary: { code: 'HU', color: 'europe' },
  Iceland: { code: 'IS', color: 'europe' },
  India: { code: 'IN', color: 'asia' },
  Indonesia: { code: 'ID', color: 'asia' },
  Iran: { code: 'IR', color: 'asia' },
  Iraq: { code: 'IQ', color: 'asia' },
  Ireland: { code: 'IE', color: 'europe' },
  Israel: { code: 'IL', color: 'asia' },
  Italy: { code: 'IT', color: 'europe' },
  Jamaica: { code: 'JM', color: 'northAmerica' },
  Japan: { code: 'JP', color: 'asia' },
  Jordan: { code: 'JO', color: 'asia' },
  Kazakhstan: { code: 'KZ', color: 'asia' },
  Kenya: { code: 'KE', color: 'africa' },
  'North Korea': { code: 'KP', color: 'asia' },
  'South Korea': { code: 'KR', color: 'asia' },
  Kuwait: { code: 'KW', color: 'asia' },
  Kyrgyzstan: { code: 'KG', color: 'asia' },
  Laos: { code: 'LA', color: 'asia' },
  Latvia: { code: 'LV', color: 'europe' },
  Lebanon: { code: 'LB', color: 'asia' },
  Lesotho: { code: 'LS', color: 'africa' },
  Liberia: { code: 'LR', color: 'africa' },
  Libya: { code: 'LY', color: 'africa' },
  Lithuania: { code: 'LT', color: 'europe' },
  Luxembourg: { code: 'LU', color: 'europe' },
  Macedonia: { code: 'MK', color: 'europe' },
  Madagascar: { code: 'MG', color: 'africa' },
  Malawi: { code: 'MW', color: 'africa' },
  Malaysia: { code: 'MY', color: 'asia' },
  Mali: { code: 'ML', color: 'africa' },
  Mauritania: { code: 'MR', color: 'africa' },
  Mauritius: { code: 'MU', color: 'africa' },
  Mexico: { code: 'MX', color: 'northAmerica' },
  Moldova: { code: 'MD', color: 'europe' },
  Mongolia: { code: 'MN', color: 'asia' },
  Montenegro: { code: 'ME', color: 'europe' },
  Morocco: { code: 'MA', color: 'africa' },
  Mozambique: { code: 'MZ', color: 'africa' },
  Myanmar: { code: 'MM', color: 'asia' },
  Namibia: { code: 'NA', color: 'africa' },
  Nepal: { code: 'NP', color: 'asia' },
  Netherlands: { code: 'NL', color: 'europe' },
  'New Zealand': { code: 'NZ', color: 'oceania' },
  Nicaragua: { code: 'NI', color: 'northAmerica' },
  Niger: { code: 'NE', color: 'africa' },
  Nigeria: { code: 'NG', color: 'africa' },
  Norway: { code: 'NO', color: 'europe' },
  Oman: { code: 'OM', color: 'asia' },
  Pakistan: { code: 'PK', color: 'asia' },
  Panama: { code: 'PA', color: 'northAmerica' },
  'Papua New Guinea': { code: 'PG', color: 'oceania' },
  Paraguay: { code: 'PY', color: 'southAmerica' },
  Peru: { code: 'PE', color: 'southAmerica' },
  Philippines: { code: 'PH', color: 'asia' },
  Poland: { code: 'PL', color: 'europe' },
  Portugal: { code: 'PT', color: 'europe' },
  'Puerto Rico': { code: 'PR', color: 'northAmerica' },
  Qatar: { code: 'QA', color: 'asia' },
  Romania: { code: 'RO', color: 'europe' },
  Russia: { code: 'RU', color: 'europe' },
  Rwanda: { code: 'RW', color: 'africa' },
  'Saudi Arabia': { code: 'SA', color: 'asia' },
  Senegal: { code: 'SN', color: 'africa' },
  Serbia: { code: 'RS', color: 'europe' },
  'Sierra Leone': { code: 'SL', color: 'africa' },
  Singapore: { code: 'SG', color: 'asia' },
  Slovakia: { code: 'SK', color: 'europe' },
  Slovenia: { code: 'SI', color: 'europe' },
  'Solomon Islands': { code: 'SB', color: 'oceania' },
  Somalia: { code: 'SO', color: 'africa' },
  'South Africa': { code: 'ZA', color: 'africa' },
  Spain: { code: 'ES', color: 'europe' },
  'Sri Lanka': { code: 'LK', color: 'asia' },
  Sudan: { code: 'SD', color: 'africa' },
  Suriname: { code: 'SR', color: 'southAmerica' },
  Swaziland: { code: 'SZ', color: 'africa' },
  Sweden: { code: 'SE', color: 'europe' },
  Switzerland: { code: 'CH', color: 'europe' },
  Syria: { code: 'SY', color: 'asia' },
  Taiwan: { code: 'TW', color: 'asia' },
  Tajikistan: { code: 'TJ', color: 'asia' },
  Tanzania: { code: 'TZ', color: 'africa' },
  Thailand: { code: 'TH', color: 'asia' },
  Togo: { code: 'TG', color: 'africa' },
  'Trinidad and Tobago': { code: 'TT', color: 'northAmerica' },
  Tunisia: { code: 'TN', color: 'africa' },
  Turkey: { code: 'TR', color: 'europe' },
  Turkmenistan: { code: 'TM', color: 'asia' },
  Uganda: { code: 'UG', color: 'africa' },
  Ukraine: { code: 'UA', color: 'europe' },
  UAE: { code: 'AE', color: 'asia' },
  'United Kingdom': { code: 'GB', color: 'europe' },
  'United States of America': { code: 'US', color: 'northAmerica' },
  Uruguay: { code: 'UY', color: 'southAmerica' },
  Uzbekistan: { code: 'UZ', color: 'asia' },
  Venezuela: { code: 'VE', color: 'southAmerica' },
  Vietnam: { code: 'VN', color: 'asia' },
  Yemen: { code: 'YE', color: 'asia' },
  Zambia: { code: 'ZM', color: 'africa' },
  Zimbabwe: { code: 'ZW', color: 'africa' },
};

export default mapData;
